name: Simple Workflow
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: MY_NAME
        run: echo "${{ vars.MY_NAME }}"
    
      - name: FAMILY_NAME
        run: echo "${{ secrets.MY_FAMILY_NAME }}"
