name: Simple Workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "checkout code"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "running tests"
